### ISSUE TITLE
handlerLondon has unnecesary url fed in

### ISSUE THREAD

**Issue by RohanSSS** [FAC-Sixteen/Week5-BARb#10]
feeding and unneccessary url into handleLondon in the router. The function handleLondon doesn't have a third argument. and the url that is being fed is already hard coded into the api request inside the handler function

**Comment by sylv1ah** [comment]
maybe you could add the url argument instead of the actual url and assign the url in the handleLondon handler much like you did with your handleLondonBoroughs handler

**Comment by bantek89** [comment]
commented out for later - we want to get this function working eventually!
