### ISSUE TITLE
tip for button eventListener

### ISSUE THREAD

**Issue by RohanSSS** [FAC-Sixteen/Week5-BARb#14]
in order to add the eventListener to all the button, you could generate a list of everything with class=form__button, and iterate though it. `getElementsByClassName` returns an nodeList of everything matching.

or like suggested in #11 you could add the eventListener as you generate the buttons in your js

**Comment by oliverjam** [comment]
`getElementsByClassName` actually returns a live [HTMLCollection](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCollection), which is different from a NodeList in a few important ways. The main one is that it's live, which means it could be different every time you access it. It's generally safer to use `querySelectorAll` (which does return a static NodeList)

**Comment by bantek89** [comment]
thanks for this, good to know!
