### ISSUE TITLE
Great idea for an app! 💡

### ISSUE THREAD

**Issue by aniablaziak** [FAC-Sixteen/Week5-BARb#16]
It's such a good idea for an app and it has a cool name 😄 I also really like your design with a clickable map, I see that it might have been difficult to execute it over just two days but it's great that you gave it a try. 
Just a minor thing: the app is called CO2-MUCH in the README but the title on the page says Fly With Me! 😅

**Comment by starsuit** [comment]
Please make it work so I can use it! 🙏🏻

**Comment by sylv1ah** [comment]
Yess love the concept! 💫

**Comment by bantek89** [comment]
danke :))))
