### ISSUE TITLE
Perhaps a solution to deployment

### ISSUE THREAD

**Issue by teenie-quaggard** [FAC-Sixteen/Week5-BARb#7]
Not 100%, but I think that your app may not be deploying because your start script doesn't match your Procfile script. Heroku may be getting confused.

You might try creating a 'dev' script for development (with nodemon) and leaving your start script a node server start.

ex:
```"dev" : "nodemon src/server.js"```
```"start" : "node src/server.js```

**Comment by teenie-quaggard** [comment]
oops! I forgot the end quotation mark on the start script, but you get the point :)

**Comment by bantek89** [comment]
it was the filenames in the end!
