### ISSUE TITLE
Filename capital or camelcase

### ISSUE THREAD

**Issue by RohanSSS** [FAC-Sixteen/Week5-BARb#8]
when cloned the file boroughFunc.js seems to be capitalised, while its required with camelcase in the code.
Github doesn't really like changing the name of files when it has an existing version of the file already uploaded with a different name. you could try deleting the file, and adding it again with the new name, or maybe it might be renamable in the github website itself

**Comment by RohanSSS** [comment]
This also may be the reason that heroku isn't working

**Comment by oliverjam** [comment]
macOS has a case _insensitive_ filesystem by default, which means it won't care what the file is called. Unfortunately Linux systems (including almost all hosts, and Github) are case _sensitive_

**Comment by bobbysebolao** [comment]
Thanks for spotting this!

**Comment by bobbysebolao** [comment]
Thanks for spotting this!

**Comment by bantek89** [comment]
this was the reason heroku wasn't working, fixed now thanks :))
