### ISSUE TITLE
Commit messages & branch naming

### ISSUE THREAD

**Issue by teenie-quaggard** [FAC-Sixteen/Week5-BARb#9]
One thing that I've been told is that commit messages should be written in the present.

ie: 
"Added DOM air quality index display and map click event listener" 

should be written as:

"Add DOM air quality index display and map click event listener"

This is a very small detail, but is common practice.
Also, it would be great to see better naming with your branches.

I see that one merged branch was called boroughfunc. Ideally, the name of the branch would tell you what is happening in that branch. 
So....perhaps something like the following would allow history to be tracked in your branches.

feature/api-response-data-sorting

**Comment by bobbysebolao** [comment]
Thanks for this comment, that's really interesting about the present tense commit messages!
